### PR TITLE
Fix Oslash and oslash sidebearings

### PR DESCRIPTION
**Pull request by m4rc1e**
Fixes https://github.com/google/fonts/issues/1851

@jpt will get you some diffs

### CODE REVIEW

**Comment by jpt** [comment]
Thanks @m4rc1e ! I tend to agree with #41 so this may change again soon

**Comment by m4rc1e** [comment]
Np! For the time being we should merge this.

**Comment by m4rc1e** [comment]
Here are the diffs I promised, [Barlow-std_diffenator.zip](https://github.com/jpt/barlow/files/2884083/Barlow-std_diffenator.zip).

Apart from the Oslash some other minor changes have occurred. These have been caused by Glyphsapp. Judging by the diff images and reports, they're not noticeable to the human eye. Please inspect the html report for each font to see for yourself.

If you're happy, please merge and I will push a new version to GF. I hope we can solve this by Friday.

**Comment by m4rc1e** [comment]
Here are the diffs for the Condensed, [barlow_condensed.zip](https://github.com/jpt/barlow/files/2884512/barlow_condensed.zip) and SemiCondensed, 
[barlow_semicondensed.zip](https://github.com/jpt/barlow/files/2884567/barlow_semicondensed.zip)

Let me know if you're happy and I'll push to GF once merged.

**Comment by jpt** [comment]
Great, thanks @m4rc1e -- and understood on timeline; I'll take a look at the diffs in the morning.

**Comment by jpt** [comment]
lgtm, thank you @m4rc1e !

**Comment by carnevalle** [comment]
Hi @jpt

This is still an issue 
https://github.com/google/fonts/issues/4055

**Comment by jpt** [comment]
Thanks @carnevalle. I think it has been a few years since that alternate ø was included in a Barlow release, after a number of emails and issues created by Norwegian users. 

There is an entirely re-spaced, re-kerned Barlow in the 1.5 branch (https://github.com/jpt/barlow/tree/1.5) that improves Barlow in a variety of other ways as well. I'm currently working on #10, but I could also bump up to a more incremental release. I'd have to take a look and see how it does with fontbakery.

**Pull request merged**
